### ISSUE TITLE
푸틀에서 terminology/essential.po의 번역 제안 

### ISSUE THREAD

**Issue by rlouol** [libreoffice-kr/issue#1]
reply 답변

resolution 해상도

response 응답

rotate 회전

route 경로

router 라우터

runtime 실행 시간

scanner 스캐너

scratch 스크래치

sector 부채꼴

sender 보내는 사람

server 서버

setup 설정

shape 도형

share 공유

sharp 올림표(#)

sheet 시트

shell 쉘(명령어 해석기)

shortcut 바로가기

shrink 축소

shut down 정지

sign 서명

signal 신호

site 사이트

slide 슬라이드

slot 슬롯

smooth 곡선

span 셀 걸치기

spawn 스폰 <= https://en.wikipedia.org/wiki/Spawn_(computing)

specify 이름 지정

speed 속도

spelling 맞춤법

split 나누기

state 상태

step 단계

storage 저장소

stream 스트림

stretch 늘리기

stroke 윤곽선

stub 스텁

style 스타일

sub directory 서브 디렉토리

submission 제출

submit 제출

subscription 구독

succeed 계승

suggest 제안

suggestion 제안

sum (noun) 합계 (명사)

sum (verb) 합계 (동사)

suspicious 의심스러운

switch 전환

symbol 기호

syntax 구문

tab 탭

table 표

template 템플릿

texture 질감

tick 틱

tip 팁

tool box 도구 상자

traffic 트래픽

transfer 전송

transform 변형

trouble shoot 오류 진단

tweak 수정

type (noun) 타입 (명사)

type (verb) 타입 (동사)

unavailable 사용 불가

under line 밑줄

undo 되돌리기

uninstall 삭제

reachable 접근 가능

readable 읽기 가능

unspecified 지정되지 않음

unsubscribe 구독 취소

update 업데이트

upload 업로드

upper case 대문자

usage 사용법

valid 유효함

vector 벡터

verbose 자세히

verify 검증

video 동영상

viewer 뷰어

volume 음량

warn 경고

web 웹

web cam 웹캠

web master 웹 마스터

wi fi 와이파이

wild card 와일드 카드

wizard 마법사

word processor 워드 프로세서

work group 작업 그룹

work station 워크 스테이션

wrap 줄 바꿈

총 103개를 제안을 했고 제출은 제가 pootle에서 어떻게 확인하는지 모르겠네요...

그리고 그 외에도 다른 폴더에도 몇 개의 스크립트들을 번역을 제안하고 제출을 하였습니다.

**Comment by studioego** [comment]
늦었지만 이상 닫습니다
